CREATE TABLE Account (id int(11) NOT NULL AUTO_INCREMENT, `user` varchar(50), password varchar(500), PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Address (id int(11) NOT NULL AUTO_INCREMENT, street varchar(50), city varchar(50), region varchar(50), PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Bill (id int(11) NOT NULL AUTO_INCREMENT, time varchar(50), Employeesid int(11) NOT NULL, Orderid int(11) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Book (id int(11) NOT NULL AUTO_INCREMENT, year varchar(50), author varchar(50), Itemid int(11) NOT NULL, Category_Bookid int(11) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Clothes (id int(11) NOT NULL AUTO_INCREMENT, colors varchar(50), `size` varchar(50), Itemid int(11) NOT NULL, Category_Clothesid int(11) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Customer (id int(11) NOT NULL AUTO_INCREMENT, Personid int(11) NOT NULL, TypeCustomerid int(11) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Electronics (id int(11) NOT NULL AUTO_INCREMENT, `size` varchar(100), weight float, Itemid int(11) NOT NULL, Category_Electronicsid int(11) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Employees (id int(11) NOT NULL AUTO_INCREMENT, salary int(11), position varchar(50), Personid int(11) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE FullName (id int(11) NOT NULL AUTO_INCREMENT, firstname varchar(50), lastname varchar(50), PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Item (id int(11) NOT NULL AUTO_INCREMENT, name varchar(50), price int(11), amount int(11), Publisherid int(11) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE `Order` (id int(11) NOT NULL AUTO_INCREMENT, payment int(11), time_order varchar(50), Customerid int(11) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE OrderDetail (id int(11) NOT NULL AUTO_INCREMENT, amount int(11), payment int(11), Itemid int(11) NOT NULL, Orderid int(11) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Person (id int(11) NOT NULL AUTO_INCREMENT, Accountid int(11) NOT NULL, FullNameid int(11) NOT NULL, Addressid int(11) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Publisher (id int(11) NOT NULL AUTO_INCREMENT, name varchar(50), address varchar(50), PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE TypeCustomer (id int(11) NOT NULL AUTO_INCREMENT, type varchar(50), PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Category_Electronics (id int(11) NOT NULL AUTO_INCREMENT, name_electronic varchar(100), PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Category_Clothes (id int(11) NOT NULL AUTO_INCREMENT, name_clothes varchar(100), PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
CREATE TABLE Category_Book (id int(11) NOT NULL AUTO_INCREMENT, name_book varchar(100), PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET UTF8;
ALTER TABLE Person ADD INDEX FKPerson573846 (Accountid), ADD CONSTRAINT FKPerson573846 FOREIGN KEY (Accountid) REFERENCES Account (id);
ALTER TABLE Person ADD INDEX FKPerson907952 (FullNameid), ADD CONSTRAINT FKPerson907952 FOREIGN KEY (FullNameid) REFERENCES FullName (id);
ALTER TABLE Person ADD INDEX FKPerson628834 (Addressid), ADD CONSTRAINT FKPerson628834 FOREIGN KEY (Addressid) REFERENCES Address (id);
ALTER TABLE Customer ADD INDEX FKCustomer218811 (Personid), ADD CONSTRAINT FKCustomer218811 FOREIGN KEY (Personid) REFERENCES Person (id);
ALTER TABLE Customer ADD INDEX FKCustomer139769 (TypeCustomerid), ADD CONSTRAINT FKCustomer139769 FOREIGN KEY (TypeCustomerid) REFERENCES TypeCustomer (id);
ALTER TABLE Employees ADD INDEX FKEmployees218008 (Personid), ADD CONSTRAINT FKEmployees218008 FOREIGN KEY (Personid) REFERENCES Person (id);
ALTER TABLE Item ADD INDEX FKItem436725 (Publisherid), ADD CONSTRAINT FKItem436725 FOREIGN KEY (Publisherid) REFERENCES Publisher (id);
ALTER TABLE Electronics ADD INDEX FKElectronic369294 (Itemid), ADD CONSTRAINT FKElectronic369294 FOREIGN KEY (Itemid) REFERENCES Item (id);
ALTER TABLE Clothes ADD INDEX FKClothes721978 (Itemid), ADD CONSTRAINT FKClothes721978 FOREIGN KEY (Itemid) REFERENCES Item (id);
ALTER TABLE Book ADD INDEX FKBook426693 (Itemid), ADD CONSTRAINT FKBook426693 FOREIGN KEY (Itemid) REFERENCES Item (id);
ALTER TABLE `Order` ADD INDEX FKOrder558759 (Customerid), ADD CONSTRAINT FKOrder558759 FOREIGN KEY (Customerid) REFERENCES Customer (id);
ALTER TABLE OrderDetail ADD INDEX FKOrderDetai706933 (Itemid), ADD CONSTRAINT FKOrderDetai706933 FOREIGN KEY (Itemid) REFERENCES Item (id);
ALTER TABLE OrderDetail ADD INDEX FKOrderDetai760088 (Orderid), ADD CONSTRAINT FKOrderDetai760088 FOREIGN KEY (Orderid) REFERENCES `Order` (id);
ALTER TABLE Bill ADD INDEX FKBill97389 (Employeesid), ADD CONSTRAINT FKBill97389 FOREIGN KEY (Employeesid) REFERENCES Employees (id);
ALTER TABLE Bill ADD INDEX FKBill72017 (Orderid), ADD CONSTRAINT FKBill72017 FOREIGN KEY (Orderid) REFERENCES `Order` (id);
ALTER TABLE Electronics ADD INDEX FKElectronic790052 (Category_Electronicsid), ADD CONSTRAINT FKElectronic790052 FOREIGN KEY (Category_Electronicsid) REFERENCES Category_Electronics (id);
ALTER TABLE Clothes ADD INDEX FKClothes205311 (Category_Clothesid), ADD CONSTRAINT FKClothes205311 FOREIGN KEY (Category_Clothesid) REFERENCES Category_Clothes (id);
ALTER TABLE Book ADD INDEX FKBook255533 (Category_Bookid), ADD CONSTRAINT FKBook255533 FOREIGN KEY (Category_Bookid) REFERENCES Category_Book (id);
